# Setup
title: Luca Mayer
subtitle: "You're going to love this."
tagline: sailing
url: https://
paginate: 1
baseurl: ""
about: "about"
permalink: pretty

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Luca
  url:
  email: mayer@zeppel.eu

# Custom vars
version: 3.0.0
